In [154]:
import pandas as pd
import numpy as np

In [155]:
data = pd.read_csv("ciftci-egitim-envanteri-veri.csv", sep = ";")

In [156]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   s.no                                  31 non-null     float64
 1   ilcesi                                31 non-null     object
 2   2015_egitim_verilen_mahalle_sayisi    31 non-null     float64
 3   2015_kursiyer_sayisi                  31 non-null     float64
 4   2016_egitim_verilen_mahalle_sayisi    31 non-null     float64
 5   2016_kursiyer_sayisi                  31 non-null     float64
 6   2017_egitim_verilen_mahalle_sayisi    31 non-null     float64
 7   2017_kursiyer_sayisi                  31 non-null     float64
 8   2018_egitim_verilen_mahalle_sayisi    31 non-null     float64
 9   2018_kursiyer_sayisi                  31 non-null     float64
 10  2019_egitim_verilen_mahalle_sayisi    31 non-null     float64
 11  2019_kursiyer_sayisi                  31 non-null     float64
 12  2020_egitim_verilen_mahalle_sayisi    31 non-null     float64
 13  2020_kursiyer_sayisi                  31 non-null     float64
 14  2021_egitim_verilen_mahalle_sayisi    31 non-null     float64
 15  2021_kursiyer_sayisi                  31 non-null     float64
 16  toplam_egitim_verilen_mahalle_sayisi  31 non-null     float64
 17  toplam_kursiyer_sayisi                31 non-null     float64
dtypes: float64(17), object(1)
memory usage: 4.6+ KB

In [182]:
data

,ilcesi,2015_egitim_verilen_mahalle_sayisi,2015_kursiyer_sayisi,2016_egitim_verilen_mahalle_sayisi,2016_kursiyer_sayisi,2017_egitim_verilen_mahalle_sayisi,2017_kursiyer_sayisi,2018_egitim_verilen_mahalle_sayisi,2018_kursiyer_sayisi,2019_egitim_verilen_mahalle_sayisi,2019_kursiyer_sayisi,2020_egitim_verilen_mahalle_sayisi,2020_kursiyer_sayisi,2021_egitim_verilen_mahalle_sayisi,2021_kursiyer_sayisi,toplam_egitim_verilen_mahalle_sayisi,toplam_kursiyer_sayisi
0,AHIRLI,10,973,8,629,6,214,4,168,1,36,2,34,3,3,34,2057
1,AKÖREN,9,619,9,621,5,344,6,262,4,235,11,277,6,63,50,2421
2,AKŞEHİR,12,1754,23,1709,19,1426,20,1334,13,636,14,386,12,128,113,7373
3,ALTINEKİN,10,1407,12,380,6,238,5,156,4,152,4,75,0,0,41,2408
4,BEYŞEHİR,23,2207,32,2226,21,1317,24,1564,20,1491,16,353,14,210,150,9368
5,BOZKIR,17,1518,17,1005,15,790,13,464,9,429,14,243,20,271,105,472
6,CİHANBEYLİ,8,510,18,1426,6,240,5,200,1,22,3,74,4,38,45,251
7,ÇELTİK,4,176,5,671,3,92,1,60,1,39,2,16,1,4,17,1058
8,ÇUMRA,10,1486,25,1493,14,1115,19,671,6,331,9,300,16,159,99,5555
9,DERBENT,6,490,10,834,7,440,5,175,2,76,5,250,2,17,37,2282
10,DEREBUCAK,5,505,10,1022,5,234,5,291,2,115,2,63,1,47,30,2277
11,DOĞANHİSAR,12,1831,17,1438,14,1774,13,1555,9,541,9,324,9,167,83,763
12,EMİRGAZİ,4,783,7,743,1,150,3,191,4,120,1,24,3,12,23,2023
13,EREĞLİ,13,1051,13,938,8,381,6,390,6,492,8,133,9,85,63,347
14,GÜNEYSINIR,11,1086,12,825,9,314,9,536,6,310,6,308,4,38,57,3417
15,HADİM,16,1319,18,704,16,687,6,182,8,363,7,132,6,63,77,345
16,HALKAPINAR,6,985,9,272,10,384,5,176,3,110,3,96,3,79,39,2102
17,HÜYÜK,16,16,16,1775,17,1516,18,1086,14,1022,14,528,11,204,106,7731
18,ILGIN,16,1491,25,1827,15,887,19,1199,11,524,8,251,6,47,100,6226
19,KADINHANI,8,245,18,1084,11,430,15,831,12,824,6,73,8,76,78,3563
20,KARAPINAR,9,771,16,1018,8,492,4,172,4,167,7,187,4,107,52,2914
21,KARATAY,5,320,5,1097,3,168,8,2022,6,1945,11,1203,11,539,49,8806
22,KULU,3,65,14,898,9,310,5,108,4,168,7,133,7,126,49,1808
23,MERAM,28,1872,18,2007,20,2983,23,3008,13,2382,16,1043,26,568,144,13863
24,SARAYÖNÜ,11,692,13,1482,12,515,8,208,5,152,4,95,7,100,60,3244
25,SELÇUKLU,9,470,13,1717,9,1466,11,2579,8,2545,8,1028,7,796,65,10601
26,SEYDİŞEHİR,13,1845,27,1586,12,701,22,1337,17,955,13,177,16,96,120,6697
27,TAŞKENT,8,774,8,553,4,152,3,102,1,26,4,49,1,53,29,1709
28,TUZLUKÇU,2,110,8,754,1,73,2,180,1,43,2,164,2,5,18,1329
29,YALIHÜYÜK,3,159,2,282,2,68,2,50,1,50,3,73,3,25,16,707
30,YUNAK,7,385,11,876,3,102,1,48,1,20,3,39,5,41,31,1511

In [158]:
data.drop(columns="s.no", inplace=True)

In [159]:
data.drop(index=31, inplace=True)

In [160]:
data["2015_egitim_verilen_mahalle_sayisi"] = data["2015_egitim_verilen_mahalle_sayisi"].astype(int)

In [161]:
data["2015_egitim_verilen_mahalle_sayisi"]

0     10
1      9
2     12
3     10
4     23
5     17
6      8
7      4
8     10
9      6
10     5
11    12
12     4
13    13
14    11
15    16
16     6
17    16
18    16
19     8
20     9
21     5
22     3
23    28
24    11
25     9
26    13
27     8
28     2
29     3
30     7
Name: 2015_egitim_verilen_mahalle_sayisi, dtype: int64

In [162]:
for i in range(0,31):
    data["2015_kursiyer_sayisi"] = data["2015_kursiyer_sayisi"].astype(str)
    if data["2015_kursiyer_sayisi"][i].endswith(".0"):
        data["2015_kursiyer_sayisi"][i] = data["2015_kursiyer_sayisi"][i][:-2]
        data["2015_kursiyer_sayisi"][i] = int(data["2015_kursiyer_sayisi"][i])
    else:
        data["2015_kursiyer_sayisi"][i] = data["2015_kursiyer_sayisi"][i].replace(".","")
        data["2015_kursiyer_sayisi"][i] = int(data["2015_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/912907967.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2015_kursiyer_sayisi"][i] = data["2015_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/912907967.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2015_kursiyer_sayisi"][i] = int(data["2015_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/912907967.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2015_kursiyer_sayisi"][i] = data["2015_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/912907967.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2015_kursiyer_sayisi"][i] = int(data["2015_kursiyer_sayisi"][i])

In [163]:
data["2015_kursiyer_sayisi"][17] = int(data["2015_kursiyer_sayisi"][17])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/918562389.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2015_kursiyer_sayisi"][17] = int(data["2015_kursiyer_sayisi"][17])

In [164]:
data["2015_kursiyer_sayisi"]

0      973
1      619
2     1754
3     1407
4     2207
5     1518
6      510
7      176
8     1486
9      490
10     505
11    1831
12     783
13    1051
14    1086
15    1319
16     985
17      16
18    1491
19     245
20     771
21     320
22      65
23    1872
24     692
25     470
26    1845
27     774
28     110
29     159
30     385
Name: 2015_kursiyer_sayisi, dtype: object

In [165]:
type(data["2016_kursiyer_sayisi"][10])

numpy.float64

In [166]:
data["2016_kursiyer_sayisi"]

0     629.000
1     621.000
2       1.709
3     380.000
4       2.226
5       1.005
6       1.426
7     671.000
8       1.493
9     834.000
10      1.022
11      1.438
12    743.000
13    938.000
14    825.000
15    704.000
16    272.000
17      1.775
18      1.827
19      1.084
20      1.018
21      1.097
22    898.000
23      2.007
24      1.482
25      1.717
26      1.586
27    553.000
28    754.000
29    282.000
30    876.000
Name: 2016_kursiyer_sayisi, dtype: float64

In [167]:
for i in range(0,31):
    data["2016_kursiyer_sayisi"] = data["2016_kursiyer_sayisi"].astype(str)
    if data["2016_kursiyer_sayisi"][i].endswith(".0"):
        data["2016_kursiyer_sayisi"][i] = data["2016_kursiyer_sayisi"][i][:-2]
        data["2016_kursiyer_sayisi"][i] = int(data["2016_kursiyer_sayisi"][i])
    else:
        data["2016_kursiyer_sayisi"][i] = data["2016_kursiyer_sayisi"][i].replace(".","")
        data["2016_kursiyer_sayisi"][i] = int(data["2016_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/309051891.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2016_kursiyer_sayisi"][i] = data["2016_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/309051891.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2016_kursiyer_sayisi"][i] = int(data["2016_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/309051891.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2016_kursiyer_sayisi"][i] = data["2016_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/309051891.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2016_kursiyer_sayisi"][i] = int(data["2016_kursiyer_sayisi"][i])

In [168]:
data["2016_kursiyer_sayisi"]

0      629
1      621
2     1709
3      380
4     2226
5     1005
6     1426
7      671
8     1493
9      834
10    1022
11    1438
12     743
13     938
14     825
15     704
16     272
17    1775
18    1827
19    1084
20    1018
21    1097
22     898
23    2007
24    1482
25    1717
26    1586
27     553
28     754
29     282
30     876
Name: 2016_kursiyer_sayisi, dtype: object

In [169]:
for i in range(0,31):
    data["2017_kursiyer_sayisi"] = data["2017_kursiyer_sayisi"].astype(str)
    if data["2017_kursiyer_sayisi"][i].endswith(".0"):
        data["2017_kursiyer_sayisi"][i] = data["2017_kursiyer_sayisi"][i][:-2]
        data["2017_kursiyer_sayisi"][i] = int(data["2017_kursiyer_sayisi"][i])
    else:
        data["2017_kursiyer_sayisi"][i] = data["2017_kursiyer_sayisi"][i].replace(".","")
        data["2017_kursiyer_sayisi"][i] = int(data["2017_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/3282687052.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2017_kursiyer_sayisi"][i] = data["2017_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/3282687052.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2017_kursiyer_sayisi"][i] = int(data["2017_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/3282687052.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2017_kursiyer_sayisi"][i] = data["2017_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/3282687052.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2017_kursiyer_sayisi"][i] = int(data["2017_kursiyer_sayisi"][i])

In [170]:
for i in range(0,31):
    data["2018_kursiyer_sayisi"] = data["2018_kursiyer_sayisi"].astype(str)
    if data["2018_kursiyer_sayisi"][i].endswith(".0"):
        data["2018_kursiyer_sayisi"][i] = data["2018_kursiyer_sayisi"][i][:-2]
        data["2018_kursiyer_sayisi"][i] = int(data["2018_kursiyer_sayisi"][i])
    else:
        data["2018_kursiyer_sayisi"][i] = data["2018_kursiyer_sayisi"][i].replace(".","")
        data["2018_kursiyer_sayisi"][i] = int(data["2018_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/1561433377.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2018_kursiyer_sayisi"][i] = data["2018_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/1561433377.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2018_kursiyer_sayisi"][i] = int(data["2018_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/1561433377.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2018_kursiyer_sayisi"][i] = data["2018_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/1561433377.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2018_kursiyer_sayisi"][i] = int(data["2018_kursiyer_sayisi"][i])

In [171]:
for i in range(0,31):
    data["2019_kursiyer_sayisi"] = data["2019_kursiyer_sayisi"].astype(str)
    if data["2019_kursiyer_sayisi"][i].endswith(".0"):
        data["2019_kursiyer_sayisi"][i] = data["2019_kursiyer_sayisi"][i][:-2]
        data["2019_kursiyer_sayisi"][i] = int(data["2019_kursiyer_sayisi"][i])
    else:
        data["2019_kursiyer_sayisi"][i] = data["2019_kursiyer_sayisi"][i].replace(".","")
        data["2019_kursiyer_sayisi"][i] = int(data["2019_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2205540426.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2019_kursiyer_sayisi"][i] = data["2019_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2205540426.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2019_kursiyer_sayisi"][i] = int(data["2019_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2205540426.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2019_kursiyer_sayisi"][i] = data["2019_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2205540426.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2019_kursiyer_sayisi"][i] = int(data["2019_kursiyer_sayisi"][i])

In [172]:
for i in range(0,31):
    data["2020_kursiyer_sayisi"] = data["2020_kursiyer_sayisi"].astype(str)
    if data["2020_kursiyer_sayisi"][i].endswith(".0"):
        data["2020_kursiyer_sayisi"][i] = data["2020_kursiyer_sayisi"][i][:-2]
        data["2020_kursiyer_sayisi"][i] = int(data["2020_kursiyer_sayisi"][i])
    else:
        data["2020_kursiyer_sayisi"][i] = data["2020_kursiyer_sayisi"][i].replace(".","")
        data["2020_kursiyer_sayisi"][i] = int(data["2020_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2239451100.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2020_kursiyer_sayisi"][i] = data["2020_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2239451100.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2020_kursiyer_sayisi"][i] = int(data["2020_kursiyer_sayisi"][i])
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2239451100.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2020_kursiyer_sayisi"][i] = data["2020_kursiyer_sayisi"][i].replace(".","")
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2239451100.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2020_kursiyer_sayisi"][i] = int(data["2020_kursiyer_sayisi"][i])

In [173]:
for i in range(0,31):
    data["2021_kursiyer_sayisi"] = data["2021_kursiyer_sayisi"].astype(str)
    if data["2021_kursiyer_sayisi"][i].endswith(".0"):
        data["2021_kursiyer_sayisi"][i] = data["2021_kursiyer_sayisi"][i][:-2]
        data["2021_kursiyer_sayisi"][i] = int(data["2021_kursiyer_sayisi"][i])
    else:
        data["2021_kursiyer_sayisi"][i] = data["2021_kursiyer_sayisi"][i].replace(".","")
        data["2021_kursiyer_sayisi"][i] = int(data["2021_kursiyer_sayisi"][i])

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2425622698.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2021_kursiyer_sayisi"][i] = data["2021_kursiyer_sayisi"][i][:-2]
/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/2425622698.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["2021_kursiyer_sayisi"][i] = int(data["2021_kursiyer_sayisi"][i])

In [174]:
data["toplam_kursiyer_sayisi"] = data["toplam_kursiyer_sayisi"].astype(str).str.replace(".","")

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/4012617381.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["toplam_kursiyer_sayisi"] = data["toplam_kursiyer_sayisi"].astype(str).str.replace(".","")

In [175]:
data["toplam_kursiyer_sayisi"][29] = 707

/var/folders/jh/d35s6brj6td3270jfy770tjc0000gn/T/ipykernel_42048/4051837775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["toplam_kursiyer_sayisi"][29] = 707

In [176]:
data["toplam_kursiyer_sayisi"] = data["toplam_kursiyer_sayisi"].astype(int)
data["toplam_egitim_verilen_mahalle_sayisi"] = data["toplam_egitim_verilen_mahalle_sayisi"].astype(int)

In [177]:
data["2016_egitim_verilen_mahalle_sayisi"] = data["2016_egitim_verilen_mahalle_sayisi"].astype(int)
data["2017_egitim_verilen_mahalle_sayisi"] = data["2017_egitim_verilen_mahalle_sayisi"].astype(int)
data["2018_egitim_verilen_mahalle_sayisi"] = data["2018_egitim_verilen_mahalle_sayisi"].astype(int)
data["2019_egitim_verilen_mahalle_sayisi"] = data["2019_egitim_verilen_mahalle_sayisi"].astype(int)
data["2020_egitim_verilen_mahalle_sayisi"] = data["2020_egitim_verilen_mahalle_sayisi"].astype(int)
data["2021_egitim_verilen_mahalle_sayisi"] = data["2021_egitim_verilen_mahalle_sayisi"].astype(int)

In [178]:
data["2021_egitim_verilen_mahalle_sayisi"]

0      3
1      6
2     12
3      0
4     14
5     20
6      4
7      1
8     16
9      2
10     1
11     9
12     3
13     9
14     4
15     6
16     3
17    11
18     6
19     8
20     4
21    11
22     7
23    26
24     7
25     7
26    16
27     1
28     2
29     3
30     5
Name: 2021_egitim_verilen_mahalle_sayisi, dtype: int64

In [179]:
data

,ilcesi,2015_egitim_verilen_mahalle_sayisi,2015_kursiyer_sayisi,2016_egitim_verilen_mahalle_sayisi,2016_kursiyer_sayisi,2017_egitim_verilen_mahalle_sayisi,2017_kursiyer_sayisi,2018_egitim_verilen_mahalle_sayisi,2018_kursiyer_sayisi,2019_egitim_verilen_mahalle_sayisi,2019_kursiyer_sayisi,2020_egitim_verilen_mahalle_sayisi,2020_kursiyer_sayisi,2021_egitim_verilen_mahalle_sayisi,2021_kursiyer_sayisi,toplam_egitim_verilen_mahalle_sayisi,toplam_kursiyer_sayisi
0,AHIRLI,10,973,8,629,6,214,4,168,1,36,2,34,3,3,34,2057
1,AKÖREN,9,619,9,621,5,344,6,262,4,235,11,277,6,63,50,2421
2,AKŞEHİR,12,1754,23,1709,19,1426,20,1334,13,636,14,386,12,128,113,7373
3,ALTINEKİN,10,1407,12,380,6,238,5,156,4,152,4,75,0,0,41,2408
4,BEYŞEHİR,23,2207,32,2226,21,1317,24,1564,20,1491,16,353,14,210,150,9368
5,BOZKIR,17,1518,17,1005,15,790,13,464,9,429,14,243,20,271,105,472
6,CİHANBEYLİ,8,510,18,1426,6,240,5,200,1,22,3,74,4,38,45,251
7,ÇELTİK,4,176,5,671,3,92,1,60,1,39,2,16,1,4,17,1058
8,ÇUMRA,10,1486,25,1493,14,1115,19,671,6,331,9,300,16,159,99,5555
9,DERBENT,6,490,10,834,7,440,5,175,2,76,5,250,2,17,37,2282
10,DEREBUCAK,5,505,10,1022,5,234,5,291,2,115,2,63,1,47,30,2277
11,DOĞANHİSAR,12,1831,17,1438,14,1774,13,1555,9,541,9,324,9,167,83,763
12,EMİRGAZİ,4,783,7,743,1,150,3,191,4,120,1,24,3,12,23,2023
13,EREĞLİ,13,1051,13,938,8,381,6,390,6,492,8,133,9,85,63,347
14,GÜNEYSINIR,11,1086,12,825,9,314,9,536,6,310,6,308,4,38,57,3417
15,HADİM,16,1319,18,704,16,687,6,182,8,363,7,132,6,63,77,345
16,HALKAPINAR,6,985,9,272,10,384,5,176,3,110,3,96,3,79,39,2102
17,HÜYÜK,16,16,16,1775,17,1516,18,1086,14,1022,14,528,11,204,106,7731
18,ILGIN,16,1491,25,1827,15,887,19,1199,11,524,8,251,6,47,100,6226
19,KADINHANI,8,245,18,1084,11,430,15,831,12,824,6,73,8,76,78,3563
20,KARAPINAR,9,771,16,1018,8,492,4,172,4,167,7,187,4,107,52,2914
21,KARATAY,5,320,5,1097,3,168,8,2022,6,1945,11,1203,11,539,49,8806
22,KULU,3,65,14,898,9,310,5,108,4,168,7,133,7,126,49,1808
23,MERAM,28,1872,18,2007,20,2983,23,3008,13,2382,16,1043,26,568,144,13863
24,SARAYÖNÜ,11,692,13,1482,12,515,8,208,5,152,4,95,7,100,60,3244
25,SELÇUKLU,9,470,13,1717,9,1466,11,2579,8,2545,8,1028,7,796,65,10601
26,SEYDİŞEHİR,13,1845,27,1586,12,701,22,1337,17,955,13,177,16,96,120,6697
27,TAŞKENT,8,774,8,553,4,152,3,102,1,26,4,49,1,53,29,1709
28,TUZLUKÇU,2,110,8,754,1,73,2,180,1,43,2,164,2,5,18,1329
29,YALIHÜYÜK,3,159,2,282,2,68,2,50,1,50,3,73,3,25,16,707
30,YUNAK,7,385,11,876,3,102,1,48,1,20,3,39,5,41,31,1511

In [180]:
data["2021_kursiyer_sayisi"] = data["2021_kursiyer_sayisi"].astype(int)
data["2020_kursiyer_sayisi"] = data["2020_kursiyer_sayisi"].astype(int)
data["2019_kursiyer_sayisi"] = data["2019_kursiyer_sayisi"].astype(int)
data["2018_kursiyer_sayisi"] = data["2018_kursiyer_sayisi"].astype(int)
data["2017_kursiyer_sayisi"] = data["2017_kursiyer_sayisi"].astype(int)
data["2016_kursiyer_sayisi"] = data["2016_kursiyer_sayisi"].astype(int)
data["2015_kursiyer_sayisi"] = data["2015_kursiyer_sayisi"].astype(int)

In [181]:
data["2016_kursiyer_sayisi"]

0      629
1      621
2     1709
3      380
4     2226
5     1005
6     1426
7      671
8     1493
9      834
10    1022
11    1438
12     743
13     938
14     825
15     704
16     272
17    1775
18    1827
19    1084
20    1018
21    1097
22     898
23    2007
24    1482
25    1717
26    1586
27     553
28     754
29     282
30     876
Name: 2016_kursiyer_sayisi, dtype: int64

In [183]:
data.to_csv("/Users/o/Desktop/acik-veri-calismalari/ciftci-egitim-envanteri/yillara-gore-ilcelerde-egitim-verilen-ciftci-sayilari.csv", index=False, header=True)
data.to_excel("/Users/o/Desktop/acik-veri-calismalari/ciftci-egitim-envanteri/yillara-gore-ilcelerde-egitim-verilen-ciftci-sayilari.xlsx", index=False, header=True)